FROM ubuntu:22.04

RUN apt update && apt install -y \
    xfce4 \
    xfce4-goodies \
    tigervnc-standalone-server \
    tigervnc-common \
    novnc \
    websockify \
    chromium-browser \
    xauth \
    x11-apps \
    dbus-x11 \
    curl \
    wget \
    git \
    nano
