FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt update && apt install -y \
    x11vnc \
    xvfb \
    novnc \
    websockify \
    openbox \
    firefox-esr \
    tint2 \
    curl \
    wget \
    git \
    nano
